apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: vampi-secure
  name: vampi-secure
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 5000
  type: LoadBalancer
  selector:
    io.kompose.service: vampi-secure
