apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: vampi-vulnerable
  name: vampi-vulnerable
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vampi-vulnerable
  template:
    metadata:
      labels:
        io.kompose.service: vampi-vulnerable
    spec:
      containers:
        - env:
            - name: vulnerable
              value: "1"
          image: erev0s/vampi 
          name: vampi-vulnerable
          ports:
            - containerPort: 5000
      restartPolicy: Always
