name: Example workflow with OX Security Scan
on:
  push:
    branches:
      - pipeline_scans
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - pipeline_scans
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Run OX Security Scan to check for vulnerabilities
        with:
          ox_api_key: ${{ secrets.OX_API_KEY }}
        uses: oxsecurity/ox-block-mode@main
